# Generated by Django 5.1.4 on 2025-06-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_alter_students_batch_alter_students_year_of_study'),
        ('Events', '0003_alter_event_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sub_heads',
            field=models.ManyToManyField(blank=True, null=True, related_name='event_sub_heads', to='Authentication.swifters'),
        ),
    ]
