# Generated by Django 5.1.4 on 2025-06-29 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance_Management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expence',
            old_name='fund',
            new_name='amount',
        ),
    ]
