# Generated by Django 5.1.4 on 2025-06-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance_Management', '0003_totalfund'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='billing_no',
            field=models.CharField(default='', max_length=200),
        ),
    ]
