# Generated by Django 5.1.4 on 2025-06-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance_Management', '0004_fund_billing_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='expence',
            name='billing',
            field=models.CharField(default='', max_length=200),
        ),
    ]
