# Generated by Django 5.1.4 on 2025-06-29 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance_Management', '0005_expence_billing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expence',
            old_name='billing',
            new_name='billing_no',
        ),
    ]
