# Generated by Django 5.1.4 on 2025-06-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance_Management', '0006_rename_billing_expence_billing_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='billing_no',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='billing_no',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
