# Generated by Django 5.1.4 on 2025-06-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance_Management', '0007_alter_expence_billing_no_alter_fund_billing_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='billing_no',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
