# Generated by Django 5.1.4 on 2025-06-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_rename_treshere_trusherer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quardinators',
            name='department',
            field=models.CharField(default='cs', max_length=200),
            preserve_default=False,
        ),
    ]
