# Generated by Django 5.1.4 on 2025-06-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_quardinators_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretry',
            name='joind',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='secretry',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
