# Generated by Django 5.1.4 on 2025-06-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_remove_secretry_joind_remove_secretry_main_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='batch',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
